export default {
  connect: 'connect',
  error: 'error',
  users: 'users',
  disconnect: 'disconnect',
  newUser: 'newUser',
  delUser: 'delUser',
  invite: 'invite',
  accept: 'accept',
  reject: 'reject',
  gameInfo: 'gameInfo',
  play: 'play',
  public: {
    connect: 'connect',
    users: 'users',
    newUser: 'newUser',
    delUser: 'delUser',
    invite: 'invite',
    accept: 'accept',
    reject: 'reject',
    gameInfo: 'gameInfo',
    play: 'play',
  },
};
